CREATE TABLE student(
RN TEXT PRIMARY KEY,
NAME TEXT,
ADDRESS TEXT,
PHONE TEXT,
AGE INTEGER);

INSERT INTO student (RN,NAME,ADDRESS,PHONE,AGE)
VALUES("R1","RAM","Delhi","743",18),
("R2","SURESH","Delhi","985",18),
("R3","AMAN","Delhi","451",20),
("R4","SUJIT","Mumbai","876",20),
("R5","RAMESH","Mumbai","537",18);

SELECT * FROM student;
SELECT * FROM student WHERE AGE==18 AND ADDRESS=="Delhi";
SELECT * FROM student WHERE AGE==18 AND NAME=="RAM";
SELECT * FROM student WHERE NAME=="RAM" OR NAME=="SUJIT";
SELECT * FROM student WHERE NAME == "RAM" OR AGE == 20;
SELECT * FROM student WHERE AGE == 18 AND (NAME = 'RAM' OR NAME = 'RAMESH');
